<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EvgenPC" name="Task3tests(failed)" tests="2" failures="2" timestamp="6 May 2013 16:04:58 GMT" time="0.036" errors="0">
  <testcase name="assertLoginPositive" time="0.013" classname="com.epam.ehalavachou.selenium.test.TestLoginPositive">
    <failure type="java.lang.AssertionError" message="test 1 not work! expected [test1] but found [test2]">
      <![CDATA[java.lang.AssertionError: test 1 not work! expected [test1] but found [test2]
	at com.epam.ehalavachou.selenium.test.TestLoginPositive.assertLoginPositive(TestLoginPositive.java:9)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- assertLoginPositive -->
  <testcase name="assertLoginPositive" time="0.0" classname="com.epam.ehalavachou.selenium.test.TestLoginNegative">
    <failure type="java.lang.AssertionError" message="test 1 not work! expected [test2] but found [test1]">
      <![CDATA[java.lang.AssertionError: test 1 not work! expected [test2] but found [test1]
	at com.epam.ehalavachou.selenium.test.TestLoginNegative.assertLoginPositive(TestLoginNegative.java:9)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- assertLoginPositive -->
</testsuite> <!-- Task3tests(failed) -->
